name = "MultiFloats"
uuid = "bdf0d083-296b-4888-a5b6-7498122e68a5"
authors = ["David K. Zhang <dzhang314@gmail.com>"]
version = "1.0.4"

[deps]
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
julia = "1.6"
